### ISSUE TITLE
Version 3 does not work on web anymore: Unsupported operation Platform._environment

### ISSUE THREAD

**Issue by nstrelow** [java-james/flutter_dotenv#22]
This was super useful for web.

But now it does not work anymore.

Error:

```
Error: Unsupported operation: Platform._environment
    at Object.throw_ [as throw] (http://localhost:54868/dart_sdk.js:4361:11)
    at Function._environment (http://localhost:54868/dart_sdk.js:55060:17)
    at Function.get environment [as environment] (http://localhost:54868/dart_sdk.js:55118:32)
    at Function.get environment [as environment] (http://localhost:54868/dart_sdk.js:54966:27)
    at Object.clean (http://localhost:54868/packages/flutter_dotenv/src/dotenv.dart.lib.js:42:118)
    at load (http://localhost:54868/packages/flutter_dotenv/src/dotenv.dart.lib.js:49:14)
    at load.next (<anonymous>)
    at runBody (http://localhost:54868/dart_sdk.js:38027:34)
...
```

**Comment by java-james** [comment]
Thanks for raising the issue. dart:io is included in v3 to include platform support.
I think removing this explicit platform support from the lib and exposing a merge method or similasr so consumers can achieve the same env will be the answer here.

I will create a release with this asap to allow web support.

**Comment by nstrelow** [comment]
Awesome, thanks so much.

**Comment by java-james** [comment]
Release complete - Please try out [latest release](https://pub.dev/packages/flutter_dotenv) and let me know if this is working as expected for you on web.

**Comment by nstrelow** [comment]
Works now, thanks a lot :D

**Comment by itapai** [comment]
I am getting the same issue even tho I'm using the latest release (5.0.2)

```
Error: Unsupported operation: Platform._environment
    at Object.throw_ [as throw] (http://localhost:42767/dart_sdk.js:5063:11)
    at Function._environment (http://localhost:42767/dart_sdk.js:57141:17)
    at Function.get environment [as environment] (http://localhost:42767/dart_sdk.js:57199:32)
    at Function.get environment [as environment] (http://localhost:42767/dart_sdk.js:57042:27)
    at main (http://localhost:42767/packages/app/main.dart.lib.js:23:56)
    ...
```

**Comment by PaoloDooM** [comment]
> I am getting the same issue even tho I'm using the latest release (5.0.2)
> 
> ```
> Error: Unsupported operation: Platform._environment
>     at Object.throw_ [as throw] (http://localhost:42767/dart_sdk.js:5063:11)
>     at Function._environment (http://localhost:42767/dart_sdk.js:57141:17)
>     at Function.get environment [as environment] (http://localhost:42767/dart_sdk.js:57199:32)
>     at Function.get environment [as environment] (http://localhost:42767/dart_sdk.js:57042:27)
>     at main (http://localhost:42767/packages/app/main.dart.lib.js:23:56)
>     ...
> ```

me too...

**Comment by jugbeep** [comment]
This is happening to me too on 5.0.2

**Comment by Howakyl** [comment]
I also have been running into this error. Has anyone found a solution to this? I am running on 5.0.2 as well.
