### ISSUE TITLE
[Add to app] android: Unhandled Exception: Instance of 'FileNotFoundError'

### ISSUE THREAD

**Issue by kimmy-wang** [java-james/flutter_dotenv#59]
```
2022-05-19 21:10:06.868 6663-6703/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Instance of 'FileNotFoundError'
    #0      DotEnv._getEntriesFromFile (package:flutter_dotenv/src/dotenv.dart:98:7)
    <asynchronous suspension>
    #1      DotEnv.load (package:flutter_dotenv/src/dotenv.dart:65:27)
    <asynchronous suspension>
    #2      loadEnv (package:meetu_module/main.dart:118:5)
    <asynchronous suspension>
    #3      main (package:meetu_module/main.dart:52:3)
    <asynchronous suspension>
```

**Comment by JoseTeixeiraMendesJunior** [comment]
Hello, I had the same problem.

To solve it, it is necessary to import the external files, to your pubspec.yaml, in the assets section:

`  assets:`
    `- .env`

done that, you can import the load in the file in your main function:

`  await dotenv.load(fileName: ".env");
`

Hope this helps!

**Comment by ahmdmau** [comment]
any updates for this issue?

**Comment by Apostata** [comment]
Same for me, Only when app is builded, then after a reload its works. Testing on a android emulator

**Comment by giovannilattanziocrispy** [comment]
I had the same problem.

The only way to make it work was to rename the .env file and remove the dot.

This works

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await dotenv.load(fileName: 'env.module');

  runApp(const MyApp());
}
```

To make it clear: this is only an Add-to-app problem (integrating a Flutter module in an existing Android/iOS app).
It works flawless in a normal Flutter project

**Comment by matheszabi** [comment]
<img width="1062" alt="Screenshot 2022-07-21 at 06 38 04" src="https://user-images.githubusercontent.com/506560/180124937-676652a3-9fa6-4be2-b05e-fea437732fbf.png">

ios can't load it

**Comment by KevinVegaRem** [comment]
Some issue, I fix add this:
await dotenv.load(fileName: "config.env");

assets:
- config.env
