### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by jerinho** [java-james/flutter_dotenv#72]
E/flutter (29283): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Instance of 'FileNotFoundError'
E/flutter (29283): #0      DotEnv._getEntriesFromFile (package:flutter_dotenv/src/dotenv.dart:98:7)
E/flutter (29283): <asynchronous suspension>
E/flutter (29283): #1      DotEnv.load (package:flutter_dotenv/src/dotenv.dart:65:27)
E/flutter (29283): <asynchronous suspension>
E/flutter (29283): #2      main (package:menu/main.dart:12:3)
E/flutter (29283): <asynchronous suspension>
E/flutter (29283):

**Comment by aatmmr** [comment]
@jerinho, have you added the reference to your `.env` file to the `pubspec.yaml`? Make sure the reference is located, such as, 

```yaml
flutter:
  [...]

  assets:
  - .env
```

where `assets` is in the `flutter` section.

Otherwise, check if your name is other than `.env` and if so, that the initialisation specifies the `fileName`, such as, 

```dart
await dotenv.load(fileName: ".env.yourName");
```

I hope that helps.

**Comment by fleeser** [comment]
You probably put the .env file inside of the lib folder. Instead, you should put it into the root directory one layer above.

**Comment by bleszerd** [comment]
I have the same problem.

Project structure

![image](https://user-images.githubusercontent.com/77847606/213280666-431985af-6479-4cdd-9a06-c6a59b9da072.png)

.env
```.env
TWITTER_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXX
TWITTER_API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter

  #...
  flutter_dotenv: ^5.0.2
  #...

  assets:
    - assets/icons/
    - .env
```

main.dart
```dart
WidgetsFlutterBinding.ensureInitialized();
DartPluginRegistrant.ensureInitialized();

await dotenv.load(
  fileName: ".env",
);

runApp(
  StoreProvider(
    store: appStore,
    child: const MyAppName(),
  ),
);
```

A curious fact is that I ran the exact same code a few days ago on Linux and it worked, just like when I came to Windows. As much as I believe this did not influence, I thought it best to say this.

**Comment by KevinVegaRem** [comment]
Some issue, I fix add this:
await dotenv.load(fileName: "config.env");

assets:
    - config.env

**Comment by ferrarafer** [comment]
This issue in general is because the .env file is empty. I wasted a huge amount of time until I realize this. The error should be different or should be no error on empty files.

**Comment by gargashwani** [comment]
> I have the same problem.
> 
> Project structure
> 
> ![image](https://user-images.githubusercontent.com/77847606/213280666-431985af-6479-4cdd-9a06-c6a59b9da072.png)
> 
> .env
> 
> ```dotenv
> TWITTER_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXX
> TWITTER_API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> ```
> 
> pubspec.yaml
> 
> ```yaml
> dependencies:
>   flutter:
>     sdk: flutter
> 
>   #...
>   flutter_dotenv: ^5.0.2
>   #...
> 
>   assets:
>     - assets/icons/
>     - .env
> ```
> 
> main.dart
> 
> ```dart
> WidgetsFlutterBinding.ensureInitialized();
> DartPluginRegistrant.ensureInitialized();
> 
> await dotenv.load(
>   fileName: ".env",
> );
> 
> runApp(
>   StoreProvider(
>     store: appStore,
>     child: const MyAppName(),
>   ),
> );
> ```
> 
> [flutter_build_android_31.log](https://github.com/java-james/flutter_dotenv/files/10450288/flutter_build_android_31.log)
> 
> A curious fact is that I ran the exact same code a few days ago on Linux and it worked, just like when I came to Windows. As much as I believe this did not influence, I thought it best to say this.

Saved Much Time.

Thanks

**Comment by java-james** [comment]
This has been addressed in 6.0.1. `FileNotFoundError` now includes the filename and actionable guidance in its message:

FileNotFoundError: Environment file ".env" not found. Ensure the file exists and is listed under assets in pubspec.yaml.

Additionally, `EmptyEnvFileError` now shows a distinct message so empty files are no longer misdiagnosed as missing (as @ferrarafer noted in the thread).

Thanks to everyone who helped each other troubleshoot in the comments. the new error messages are essentially the same guidance you were all providing manually.
